version: "2"
services:
  web:
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: /usr/local/bin/gunicorn adventurelookup.wsgi:application --workers 2 --forwarded-allow-ips="*" --bind 0.0.0.0:8000 --reload

  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
    driver: local
