version: "2"
services:
  web:
    restart: always
    build: ./web
    links:
      - postgres:postgres
    volumes:
      - ./web/:/app
      - ./web/static:/app/static
    env_file: .env

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/adventurelookup.conf:/etc/nginx/conf.d/adventurelookup.conf:ro
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    image: postgres
    restart: always
    volumes:
      - $DATA_DIR/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME

volumes:
  static:
    driver: local
